dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode10.1
# Not technically required but suppresses 'Ruby' in Job status message.
language: java
git:
  depth: 1
os:
  - linux
  - osx
env:
  - V=0.27.2
  - V=0.28.0
before_install:
  # Borrowed from rules_scala
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      sudo apt-get update -q
      sudo apt-get install libxml2-utils -y
      OS=linux
    fi
    if [[ $V =~ .*rc[0-9]+.* ]]; then
      PRE_RC=$(expr "$V" : '\([0-9.]*\)rc.*')
      RC_PRC=$(expr "$V" : '[0-9.]*\(rc.*\)')
      URL="https://storage.googleapis.com/bazel/${PRE_RC}/${RC_PRC}/bazel-${V}-installer-${OS}-x86_64.sh"
    else
      URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    fi
    wget -nv -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
  - cat .bazelrc.travis >> .bazelrc
script:
  - ./tools/skylint.sh
  - ./test/run_all_tests.sh ci
  - bazel build play-routes:play-routes-docs
  - bazel shutdown
before_deploy:
  - openssl aes-256-cbc -K $encrypted_90964ca3428f_key -iv $encrypted_90964ca3428f_iv -in tools/lemur_rsa.enc -out lemur_rsa -d
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ./tools/ci-stardoc-update.sh
    on:
      branch: master
      condition: $DOC_VERSION = true && $TRAVIS_OS_NAME = linux
